### ISSUE TITLE
老哥能弄个知苗的嘛

### ISSUE THREAD

**Issue by Js5759** [XiaoRIGE/SnapUpYueMiao#2]
好兄弟能弄个知苗的嘛

**Comment by XiaoRIGE** [comment]
已经上岸了，就没有继续倒腾了。
不过你可以参照一下，其实应该都差不多的

**Comment by Js5759** [comment]
我不专业，能不能辛苦好哥哥给我抢个，有偿，拜托拜托，我被折磨了







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoRIGE/SnapUpYueMiao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月30日(星期四) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoRIGE/SnapUpYueMiao] 老哥能弄个知苗的嘛 (Issue #2)





 
已经上岸了，就没有继续倒腾了。
 不过你可以参照一下，其实应该都差不多的

**Comment by XiaoRIGE** [comment]
没时间搞啊
